services:
  mediaDB:
    container_name: mediaConfigDatabase
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/create_database_schemas.sh:/docker-entrypoint-initdb.d/create_database_schemas.sh
    ports:
      - "5500:5432"

volumes:
  postgres-data:
