services:
  mediaDB:
    container_name: mediaConfigDatabase
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/init_database_schemas.sql:/docker-entrypoint-initdb.d/init_database_schemas.sql
    ports:
      - "5500:5432"
    networks:
      - app-network

  parse-app:
    build:
      context: ./DataApp/pyspark-loader/parse
      dockerfile: Dockerfile
    container_name: parser-app
    depends_on:
      - mediaDB
    ports:
      - "8005:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontendUIApp
    ports:
      - "8000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge