services:
  mediaDB:
    container_name: mediaConfigDatabase
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5500:5432"

  redis-first-storage:
    container_name: firstRedisKVStorage
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  redis-second-storage:
    container_name: secondRedisKVStorage
    image: redis/redis-stack-server:latest
    ports:
      - "6378:6379"

  rabbitmq:
    container_name: messageBrokerRabbitMQ
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  scrape-service:
    container_name: scraperService
    build:
      context: .
      dockerfile: WebCrawler/webscraper-main/Dockerfile
    ports:
      - "4090:4090"
